install.packages("devtools")
install.packages("tidyverse")
install.packages("rmarkdown")
install.packages("formatR")
install.packages("pander")
tinytex::install_tinytex()
install.packages("swirl")
swirl::install_course_github("swirldev", "R_Programming_E")
devtools::install_github("hadley/emo")