install.packages("tidyverse")
install.packages("rmarkdown")
install.packages("formatR")
tinytex::install_tinytex()
install.packages("swirl")
swirl::install_course_github("swirldev", "R_Programming_E")